# name: Deploy with Rollup

# on:
#   push:
#     branches: ['master']
#   pull_request:
#     branches: ['master']

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Node Version
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           registry-url: 'https://registry.npmjs.org'
#       - name: Install dependencies ğŸ“¦
#         run: |
#           npm i -g pnpm
#           pnpm i
#       - name: Build ğŸ—ï¸
#         run: pnpm build
#       - name: Publish ğŸš€
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
